---
- name: install python3
  apt:
    name: python3
    state: present

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: Add nodejs apt key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: Add nodejs 14.x ppa for apt repo
  apt_repository:
    repo: deb https://deb.nodesource.com/node_14.x {{ ansible_distribution_release }} main
    update_cache: yes

- name: install nodejs and npm via apt
  apt: 
    # name: ['nodejs', 'npm']
    name: nodejs=13.8.0

- name: install pm2 via npm
  npm:
    name: pm2
    global: yes