---
- name: install python3
  apt:
    name: python3
    state: present

- name: Update all packages to their latest version
  apt:
    name: "*"
    state: latest

- name: add apt key for nodesource
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: install nodejs and npm via apt
  apt: 
    name: ['nodejs', 'npm']

- name: install pm2 via npm
  npm:
    name: pm2
    global: yes