- name: Copy file with owner and permissions
  copy:
    src: /home/circleci/project/artifact.tar.gz
    dest: /etc/artifact.tar.gz
    mode: '0644'

- name: Extract artifact.tgz into /etc/backend/
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: /etc/backend/

- name: Install packages based on package.json
  npm:
    path: /etc/backend/

- name: run backend
  shell: |
    cd /etc/udapeople/
    npm i
    pm2 start npm -- run start 