global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#monitoring-instance'
    send_resolved: true