global:
  resolve_timeout: 1m
  slack_api_url: '<slack-web-hook>'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#monitoring-instance'
    send_resolved: true