global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

rule_files:
 - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093

scrape_configs:
  - job_name: 'prometheus server'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIAQ726J23LMGLYCG7L
        secret_key: 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
        port: 9100
  - job_name: 'udapeople'
    static_configs:
      - targets: ['ec2-54-205-158-167.compute-1.amazonaws.com:9100']